-- CreateTable
CREATE TABLE "PengaturanAplikasi" (
    "id" TEXT NOT NULL,
    "namaToko" TEXT,
    "alamatToko" TEXT,
    "kotaToko" TEXT,
    "provinsiToko" TEXT,
    "kodePosToko" TEXT,
    "teleponToko" TEXT,
    "emailToko" TEXT,
    "websiteToko" TEXT,
    "npwpToko" TEXT,
    "urlLogoToko" TEXT,
    "headerStruk" TEXT,
    "footerStruk" TEXT,
    "pajakAktif" BOOLEAN NOT NULL DEFAULT false,
    "namaPajak" TEXT DEFAULT 'PPN',
    "persentasePajak" DECIMAL(5,2) DEFAULT 11.00,
    "hargaTermasukPajak" BOOLEAN NOT NULL DEFAULT false,
    "prefixNomorStruk" TEXT DEFAULT 'INV/',
    "digitNomorUrutStruk" INTEGER DEFAULT 5,
    "simbolMataUang" TEXT DEFAULT 'Rp',
    "posisiSimbolMataUang" TEXT DEFAULT 'SEBELUM',
    "digitDesimalMataUang" INTEGER NOT NULL DEFAULT 0,
    "pemisahRibuan" TEXT DEFAULT '.',
    "pemisahDesimal" TEXT DEFAULT ',',
    "ukuranKertasStruk" TEXT DEFAULT '58mm',
    "cetakLogoDiStruk" BOOLEAN NOT NULL DEFAULT false,
    "otomatisCetakStruk" BOOLEAN NOT NULL DEFAULT false,
    "defaultStokMinimum" INTEGER NOT NULL DEFAULT 10,
    "temaAplikasi" TEXT NOT NULL DEFAULT 'SISTEM',
    "itemPerHalaman" INTEGER NOT NULL DEFAULT 10,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PengaturanAplikasi_pkey" PRIMARY KEY ("id")
);
